title: EScp
name: escp
base: core24
version: '0.8'
summary: High Performance File Transfer Tool with a syntax similar to SCP
license: BSD-3-Clause-LBNL
source-code: https://github.com/ESnet/EScp
description: |
  EScp is a high performace transfer tool that has a similar syntax to SCP.
  Uses SSH for authentication but data transfer defaults to port 1232 using
  AES128-GCM. EScp has been demonstrated at up to 200gbit/s in transfers
  across the United States.
grade: devel
confinement: devmode

apps:
  escp:
    command: bin/escp

#    plugs:
#      - network-bind
#      - network
#      - personal-files
#      - ssh-public-keys
#      - home
#      - removable-media
#      - hardware-observe
#      - shared-memory

parts:
  #rust-deps:
  #  plugin: nil
  #  build-packages:
  #    - curl
  #  override-pull: |
  #    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  escp:
    plugin: rust
    source: https://github.com/esnet/EScp.git

    build-packages:
      - cmake
      - libtool
      - g++
      - nasm
      - autoconf
      - libnuma-dev
      - automake
    override-build: |
      cd $SNAPCRAFT_PART_SRC
      ./mk.sh
      snapcraftctl build
    # stage-packages:
    #   - libnuma1
